{{- if and (not .Values.persistence.existingClaim) (.Values.persistence.enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "heimdall.fullname" . }}-{{ .Values.persistence.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}

{{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}

{{- if  .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}

spec:
  {{- if not (empty .Values.persistence.storageClass) }}
  storageClassName: {{ .Values.persistence.storageClass }}

  {{- end }}

  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}

  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}

{{- end }}

{{- if and (not .Values.persistence2.existingClaim) (.Values.persistence2.enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "heimdall.fullname" . }}-{{ .Values.persistence2.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}

{{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}

{{- if  .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}

spec:
  {{- if not (empty .Values.persistence2.storageClass) }}
  storageClassName: {{ .Values.persistence2.storageClass }}

  {{- end }}

  accessModes:
  {{- range .Values.persistence2.accessModes }}
    - {{ . | quote }}
  {{- end }}

  resources:
    requests:
      storage: {{ .Values.persistence2.size | quote }}

{{- end }}
